db_file: 'bot.db'

bot_url: 'https://t.me/PocketoidBot'

messages:
  responses:
    start: 'Привет! Что бы сохранять ссылки в своём Pocket аккаунте, для начала тебе необходимо дать мне на это доступ. Для этого переходи по ссылке:\n%s'
    already_authorized: 'Ты уже авторизирован. Присылай ссылку, а я ее сохраню.😊'
    success_save: 'Ссылка успешно сохранена.👌'
    unknown_command: 'Я не знаю такой комманды!🧐'
  errors:
    default: 'Произошла неизввестня ошибка!😰'
    invalid_url: 'Это не валидная ссылка!😡'
    unauthorized: 'Используй команду /start что бы авторизироваться!🥸'
    fail_to_save: 'Не удалось сохранить ссылку. Попробуй сохранить позже!😔'
